spring.application.name=cinema

server.servlet.context-path=/api/v1

logging.file.name=logs/cinema-app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

jwt.secret.key=${JWT_SECRET_KEY}

auth.cookie.secure = ${SECURITY_COOKIE_SECURE}
auth.cookie.same-site= ${SECURITY_COOKIE_SAME_SITE}

security.max-attempts=${SECURITY_MAX_ATTEMPTS}
security.website.domain=${SECURITY_WEBSITE_DOMAIN}