spring.application.name=cinema

server.servlet.context-path=/api/v1

logging.file.name=logs/cinema-app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB
# logging.level.org.springframework.security=DEBUG

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

jwt.secret.key=${JWT_SECRET_KEY}

auth.cookie.secure = ${SECURITY_COOKIE_SECURE}
auth.cookie.same-site= ${SECURITY_COOKIE_SAME_SITE}

security.csrf.enabled = ${SECURITY_CSRF_ENABLED}
security.max-attempts=${SECURITY_MAX_ATTEMPTS}
security.website.domain=${SECURITY_WEBSITE_DOMAIN}
security.cors.allowed-origins=${SECURITY_CORS_ALLOWED_ORIGINS:http://localhost:4200}


bootstrap.owner-username=${BOOTSTRAP_OWNER_USERNAME}
bootstrap.owner-password=${BOOTSTRAP_OWNER_PASSWORD}
bootstrap.owner-email=${BOOTSTRAP_OWNER_EMAIL}
bootstrap.owner-first-name=${BOOTSTRAP_OWNER_FIRST_NAME}
bootstrap.owner-last-name=${BOOTSTRAP_OWNER_LAST_NAME}
bootstrap.owner-phone-number=${BOOTSTRAP_OWNER_PHONE_NUMBER}

tmdb.api.key=${TMDB_API_KEY}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

logging.level.com.awbd.cinema=DEBUG