package com.awbd.cinema.enums;

public enum GenreType {
    ACTION, ADVENTURE, ANIMATION, COMEDY, CRIME, DOCUMENTARY,
    DRAMA, FAMILY, FANTASY, HISTORY, HORROR, MUSIC, MYSTERY,
    ROMANCE, SCI_FI, THRILLER, TV_MOVIE, WAR, WESTERN
}