app:
  cache:
    default-ttl: 5m
    caches:
      admin_movies: 15m
      public_movie_lists: 10m
      single_movies: 2h
      seat_lists: 10m
      single_seat: 30m
      screen_session_lists: 10m
      movie_session_lists: 10m
      single_screen_sessions: 10m
      room_lists: 15m
      single_room: 30m
      session_info_lists: 10m
      single_session_infos: 30m
